### ISSUE TITLE
unable to generate Env.swift at Xcode 11

### ISSUE THREAD

**Issue by ghadly** [levibostian/dotenv-ios#6]
After following the documentation none of the solutions there worked with me

```
Showing All Messages, Filtering for "dotenv".
  /Users/{user}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dotenv-ios-0.1.2/lib/dotenv-ios/generator.rb:48:in `match'

  /Users/{user}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dotenv-ios-0.1.2/lib/dotenv-ios/generator.rb:48:in `match'

  /Users/{user}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dotenv-ios-0.1.2/lib/dotenv-ios/generator.rb:48:in `block in get_env_requests'

  /Users/{user}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dotenv-ios-0.1.2/lib/dotenv-ios/generator.rb:46:in `each'

  /Users/{user}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dotenv-ios-0.1.2/lib/dotenv-ios/generator.rb:46:in `get_env_requests'

  /Users/{user}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dotenv-ios-0.1.2/lib/dotenv-ios/generator.rb:35:in `block in iterate_source'

  /Users/{user}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dotenv-ios-0.1.2/lib/dotenv-ios/generator.rb:31:in `glob'

  /Users/{user}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dotenv-ios-0.1.2/lib/dotenv-ios/generator.rb:31:in `iterate_source'

  /Users/{user}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dotenv-ios-0.1.2/lib/dotenv-ios/generator.rb:20:in `start'

  /Users/{user}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dotenv-ios-0.1.2/lib/dotenv-ios/cli.rb:24:in `initialize'

  /Users/{user}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dotenv-ios-0.1.2/bin/dotenv-ios:6:in `new'

  /Users/{user}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dotenv-ios-0.1.2/bin/dotenv-ios:6:in `<top (required)>'

  /Users/{user}/.rbenv/versions/2.6.5/bin/dotenv-ios:23:in `load'

  /Users/{user}/.rbenv/versions/2.6.5/bin/dotenv-ios:23:in `<top (required)>'

```

**Comment by levibostian** [comment]
Hey there, @georgehadly-marleyspoon 👋🏻

Could you, please, share the whole stacktrace (instead of filtering for dotenv, only. One that shows the full error) and how you got this? The stacktrace here doesn't help too much.
